// ===== Solar System Planet Data =====
const PLANETS = [
  {
    id: "sun",
    name: "Sun",
    type: "Star",
    color: 0xFDB813,
    emissive: 0xFDB813,
    radius: 5,
    orbitRadius: 0,
    orbitSpeed: 0,
    rotationSpeed: 0.002,
    tilt: 7.25,
    hasRings: false,
    description: "The Sun is the star at the center of our solar system. It is a nearly perfect ball of hot plasma, generating energy through nuclear fusion of hydrogen into helium.",
    facts: {
      "Diameter": "1,392,684 km",
      "Mass": "1.989 × 10³⁰ kg",
      "Temperature": "5,778 K (surface)",
      "Age": "4.6 billion years",
      "Type": "G2V Yellow Dwarf",
      "Composition": "73% H, 25% He",
      "Luminosity": "3.828 × 10²⁶ W",
      "Distance": "Center"
    },
    funFact: "The Sun accounts for 99.86% of all mass in the solar system. Light from the Sun takes about 8 minutes and 20 seconds to reach Earth."
  },
  {
    id: "mercury",
    name: "Mercury",
    type: "Terrestrial Planet",
    color: 0xB5B5B5,
    emissive: 0x222222,
    radius: 0.5,
    orbitRadius: 10,
    orbitSpeed: 4.15,
    rotationSpeed: 0.005,
    tilt: 0.034,
    hasRings: false,
    description: "Mercury is the smallest planet in our solar system and the closest to the Sun. It has a cratered surface similar to Earth's Moon.",
    facts: {
      "Diameter": "4,879 km",
      "Mass": "3.301 × 10²³ kg",
      "Day Length": "58.6 Earth days",
      "Year Length": "88 Earth days",
      "Moons": "0",
      "Temperature": "-180 to 430°C",
      "Distance": "57.9 M km",
      "Atmosphere": "Minimal"
    },
    funFact: "A day on Mercury (sunrise to sunrise) lasts 176 Earth days — longer than its year! Despite being closest to the Sun, Venus is actually hotter."
  },
  {
    id: "venus",
    name: "Venus",
    type: "Terrestrial Planet",
    color: 0xE8CDA0,
    emissive: 0x332200,
    radius: 0.9,
    orbitRadius: 15,
    orbitSpeed: 1.62,
    rotationSpeed: -0.002,
    tilt: 177.4,
    hasRings: false,
    description: "Venus is the second planet from the Sun and the hottest in our solar system. Its thick atmosphere traps heat in a runaway greenhouse effect.",
    facts: {
      "Diameter": "12,104 km",
      "Mass": "4.867 × 10²⁴ kg",
      "Day Length": "243 Earth days",
      "Year Length": "225 Earth days",
      "Moons": "0",
      "Temperature": "462°C avg",
      "Distance": "108.2 M km",
      "Atmosphere": "CO₂, N₂"
    },
    funFact: "Venus rotates backwards compared to most planets. A day on Venus is longer than its year — it takes 243 Earth days to rotate once but only 225 days to orbit the Sun."
  },
  {
    id: "earth",
    name: "Earth",
    type: "Terrestrial Planet",
    color: 0x4DA6FF,
    emissive: 0x112244,
    radius: 1.0,
    orbitRadius: 20,
    orbitSpeed: 1.0,
    rotationSpeed: 0.02,
    tilt: 23.44,
    hasRings: false,
    description: "Earth is the third planet from the Sun and the only known place in the universe confirmed to harbor life. About 71% of its surface is covered in water.",
    facts: {
      "Diameter": "12,756 km",
      "Mass": "5.972 × 10²⁴ kg",
      "Day Length": "24 hours",
      "Year Length": "365.25 days",
      "Moons": "1 (Luna)",
      "Temperature": "15°C avg",
      "Distance": "149.6 M km",
      "Atmosphere": "N₂, O₂"
    },
    funFact: "Earth is the only planet not named after a Greek or Roman god. It's also the densest planet in the solar system."
  },
  {
    id: "mars",
    name: "Mars",
    type: "Terrestrial Planet",
    color: 0xE27B58,
    emissive: 0x331100,
    radius: 0.7,
    orbitRadius: 26,
    orbitSpeed: 0.53,
    rotationSpeed: 0.018,
    tilt: 25.19,
    hasRings: false,
    description: "Mars is the fourth planet from the Sun, often called the 'Red Planet' due to iron oxide on its surface. It has the tallest volcano and deepest canyon in the solar system.",
    facts: {
      "Diameter": "6,792 km",
      "Mass": "6.417 × 10²³ kg",
      "Day Length": "24h 37m",
      "Year Length": "687 Earth days",
      "Moons": "2 (Phobos, Deimos)",
      "Temperature": "-65°C avg",
      "Distance": "227.9 M km",
      "Atmosphere": "CO₂ (thin)"
    },
    funFact: "Mars has the largest volcano in the solar system — Olympus Mons, which is about 2.5 times the height of Mount Everest and roughly the size of France."
  },
  {
    id: "jupiter",
    name: "Jupiter",
    type: "Gas Giant",
    color: 0xC88B3A,
    emissive: 0x221100,
    radius: 3.0,
    orbitRadius: 36,
    orbitSpeed: 0.084,
    rotationSpeed: 0.04,
    tilt: 3.13,
    hasRings: false,
    description: "Jupiter is the largest planet in our solar system. This gas giant has a turbulent atmosphere with the famous Great Red Spot — a storm larger than Earth.",
    facts: {
      "Diameter": "142,984 km",
      "Mass": "1.898 × 10²⁷ kg",
      "Day Length": "9h 56m",
      "Year Length": "11.86 years",
      "Moons": "95 known",
      "Temperature": "-110°C avg",
      "Distance": "778.5 M km",
      "Atmosphere": "H₂, He"
    },
    funFact: "Jupiter's Great Red Spot is a storm that has been raging for over 350 years. The planet is so massive it could fit all other planets inside it — twice!"
  },
  {
    id: "saturn",
    name: "Saturn",
    type: "Gas Giant",
    color: 0xE8D191,
    emissive: 0x222200,
    radius: 2.5,
    orbitRadius: 48,
    orbitSpeed: 0.034,
    rotationSpeed: 0.038,
    tilt: 26.73,
    hasRings: true,
    ringInner: 3.2,
    ringOuter: 5.0,
    ringColor: 0xC8B888,
    description: "Saturn is the sixth planet from the Sun, best known for its stunning ring system made of ice and rock particles. It is the least dense planet — it could float in water!",
    facts: {
      "Diameter": "120,536 km",
      "Mass": "5.683 × 10²⁶ kg",
      "Day Length": "10h 42m",
      "Year Length": "29.46 years",
      "Moons": "146 known",
      "Temperature": "-140°C avg",
      "Distance": "1.434 B km",
      "Rings": "7 main groups"
    },
    funFact: "Saturn's density is so low (0.687 g/cm³) that it would actually float if you could find a bathtub big enough. Its moon Titan has lakes of liquid methane!"
  },
  {
    id: "uranus",
    name: "Uranus",
    type: "Ice Giant",
    color: 0x73D5E8,
    emissive: 0x112233,
    radius: 1.6,
    orbitRadius: 60,
    orbitSpeed: 0.012,
    rotationSpeed: -0.03,
    tilt: 97.77,
    hasRings: false,
    description: "Uranus is the seventh planet from the Sun. This ice giant rotates on its side, likely due to a massive collision early in its history.",
    facts: {
      "Diameter": "51,118 km",
      "Mass": "8.681 × 10²⁵ kg",
      "Day Length": "17h 14m",
      "Year Length": "84.01 years",
      "Moons": "28 known",
      "Temperature": "-195°C avg",
      "Distance": "2.871 B km",
      "Atmosphere": "H₂, He, CH₄"
    },
    funFact: "Uranus rotates on its side at a 98° tilt, essentially rolling around the Sun like a ball. Its blue-green color comes from methane in its atmosphere."
  },
  {
    id: "neptune",
    name: "Neptune",
    type: "Ice Giant",
    color: 0x5B7FFF,
    emissive: 0x111144,
    radius: 1.5,
    orbitRadius: 72,
    orbitSpeed: 0.006,
    rotationSpeed: 0.032,
    tilt: 28.32,
    hasRings: false,
    description: "Neptune is the eighth and farthest planet from the Sun. It has the strongest winds in the solar system, reaching speeds of over 2,000 km/h.",
    facts: {
      "Diameter": "49,528 km",
      "Mass": "1.024 × 10²⁶ kg",
      "Day Length": "16h 6m",
      "Year Length": "164.8 years",
      "Moons": "16 known",
      "Temperature": "-200°C avg",
      "Distance": "4.495 B km",
      "Atmosphere": "H₂, He, CH₄"
    },
    funFact: "Neptune was the first planet located through mathematical predictions rather than direct observation. Its moon Triton orbits backwards — the only large moon to do so."
  }
];
